apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendatahub-operator
  namespace: openshift-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opendatahub-operator
  template:
    metadata:
      labels:
        name: opendatahub-operator
    spec:
      containers:
      - command:
        - opendatahub-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/opendatahub/opendatahub-operator:v1.0.4
        imagePullPolicy: Always
        name: opendatahub-operator
      serviceAccountName: opendatahub-operator
