apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  name: opendatahub
  namespace: odh-trino
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: trino
      name: trino
    - kustomizeConfig:
        # TODO: Change to production bucket when available.
        parameters:
          - name: s3_endpoint_url
            value: s3-openshift-storage.apps.zero.massopen.cloud
          - name: s3_credentials_secret
            value: odh-datacatalog-bucket
        repoRef:
          name: osc-manifests
          path: trino
      name: trino
  repos:
    - name: manifests
      uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.0
    - name: osc-manifests
      uri: https://github.com/HumairAK/os-c-odh-manifests/tarball/main
  version: v1.1.0
