---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-trino
resources:
  - kfdef.yaml
secretGenerator:
  - name: odh-datacatalog-bucket
    literals:
      - BUCKET=opf-datacatalog
    # Env vars needed: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
    envs:
      - .env
