---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odh-trino
resources:
  - kfdef.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: odh-datacatalog-bucket
    literals:
      - BUCKET=osc-demo-bucket-458a6c3f-c7e3-49c3-b95f-104ceada0703
    # Env vars needed: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
    envs:
      - .env
  - name: trino-oauth
    # Env vars needed: TRINO_OAUTH_SECRET
    envs:
      - .env2