apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
resources:
  - https://github.com/operate-first/apps/dex/base
patchesStrategicMerge:
  - dex-cm.yaml
  - dex-sa.yaml
secretGenerator:
  - name: dex-clients
    # Env vars needed: SUPERSET_SECRET
    behavior: replace
    envs:
      - .env
