dbt_project_name:
  target: dev
  outputs:
    dev:
      type: trino
      method: jwt
      user: "{{ env_var('TRINO_USER') }}"
      jwt_token: "{{ env_var('TRINO_PASSWD') }}"
      database: osc_datacommons_dev
      host: "{{ env_var('TRINO_HOST') }}"
      port: "{{ env_var('TRINO_PORT') }}"
      schema: dbt_project_name
      threads: 1
